### ISSUE TITLE
[Bug]: BCC Incompatibility 

### ISSUE THREAD

**Issue by uricus** [TheIllusiveC4/CherishedWorlds#21]
### Minecraft Version

1.19.2

### What happened?

The star icon in the list of servers from Cherished Worlds will overlay the message from the Better Compatibility Checker about the incompatibility of the modpack version on the client and server. I understand that you not must care about compatibility with another mod, but if you can please fix it.
![Java-runtime-gamma Screenshot 2023 04 25 - 07 50 11 85](https://user-images.githubusercontent.com/79373647/234177780-7ec31e93-9e45-44bc-be06-568352c9720d.png)

### How do you trigger this bug?

1. Load Cherished Worlds 6.0.5 and Better Compatibility Checker 1.0.10
2. You should to write different modpack versions in client and server BCC configs.
3. Open server list in the game and move your cursor to the red X near your server when it's online.
...

### Loader

Forge

### Loader Version

Forge - 43.2.0

### Mod Version

Cherished Worlds - 6.0.5

**Comment by TheIllusiveC4** [comment]
I looked into this and unfortunately I don't think I can resolve this on my end. It seems that BCC is rendering the tooltip on the same layer as the background and so I cannot find a way to place my rendering in between them. This might be easier on BCC's end, if they can perhaps render the tooltip on a higher level so that it lays on top of any other rendering such as mine.
