### ISSUE TITLE
[Feature]: Config for disabling the mod on some menus

### ISSUE THREAD

**Issue by MidyGamy** [TheIllusiveC4/CherishedWorlds#33]
### What is the new feature or improvement?

Have a config file so we can disable the mod on only the menus we want (so it can work with other mods)
For example, I use essential which already have a favorite tab, but cherished worlds breaks the multiplayer menu, I want to disable it only for the multiplayer menu but not the singleplayer one.

**Comment by DJtheRedstoner** [comment]
Hi, Essential developer here. I'm investigating the incompatibility between Essential and Cherished Worlds. The root cause of the issue is this: https://github.com/illusivesoulworks/cherishedworlds/blob/69b02e17c08a28049225d7004ecec0c771486a93/common/src/main/java/com/illusivesoulworks/cherishedworlds/client/favorites/FavoriteServers.java#L31-L39

This code is invoked from Fabric's `AFTER_INIT` screen event, which is after Essential modifies the server list entries. This results in Essential's changes being overwritten, breaking our Friends & Featured tabs.

I'm not sure why this code is needed at all. I removed it and everything seemed to continue to work fine, and Essential's tabs worked as expected. Clicking the star messes things up a little bit, but that's not a huge deal given everything else is functional.

**Comment by TheIllusiveC4** [comment]
Hmm, you're right. I'm not sure why that code is there either. It's been there since the inception of the feature back in 1.16, so it existed for _some_ reason but that reason alludes me after all these years. And it may very well be outdated by now.

It doesn't seem to break anything in my testing either so I don't have a problem with just removing it.
