### ISSUE TITLE
[Bug]: Crashes with Axiom 1.21

### ISSUE THREAD

**Issue by bathala-a11y** [TheIllusiveC4/CherishedWorlds#34]
### Minecraft Version

1.21.0

### What happened?

Doesn't make any sense why would it affect Axiom with your mod even though it's a small problem.

![image](https://github.com/user-attachments/assets/01e9b320-b571-4c78-b964-0550867a56f1)

### How do you trigger this bug?

1. Triggers after trying to create a world.
2.
3.
...

### Loader

Fabric

### Loader Version

0.16.0

### API Version

0.100.7+1.21

### Mod Version

Cherished Worlds 1.21 - 10.0.1

**Comment by TheIllusiveC4** [comment]
I'm unable to reproduce this, I am able to create a world with both Axiom and Cherished Worlds installed. Have you tried this with _just_ these two mods to isolate any mod conflicts?

If this is still an issue after testing that, it would be best to report it to the Axiom developer since it seems like the crash is coming from their mod.
